FROM alpine:latest

LABEL org.opencontainers.image.source=https://github.com/jadonclegg/recovery-code-encrpytor

WORKDIR /app

COPY recovery-code-encryptor ./
EXPOSE 8080
CMD [ "/app/recovery-code-encryptor" ]